import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2, UtensilsCrossed } from "lucide-react";
import { createCanteenMeal, deleteCanteenMeal, getCanteenMeals, updateCanteenMeal } from "../../service/canteenService";

const empty = { mealType: "BREAKFAST", mainDishes: "", curries: "", shortEats: "" };
export default function MealManagement() {
  const [meals, setMeals] = useState([]), [form, setForm] = useState(empty), [editingId, setEditingId] = useState(null), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const load = async () => { try { setMeals((await getCanteenMeals()).data); } catch { setError("Unable to load meals. Please try again."); } };
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); setError(""); if (![form.mainDishes, form.curries, form.shortEats].some((value) => value.trim())) { setError("Add at least one food item before publishing."); return; } setSaving(true); try { editingId ? await updateCanteenMeal(editingId, form) : await createCanteenMeal(form); setForm(empty); setEditingId(null); await load(); } catch (err) { setError(err.response?.data?.message || err.response?.data?.detail || "Could not save the meal menu."); } finally { setSaving(false); } };
  const edit = (meal) => { setForm({ mealType: meal.mealType, mainDishes: meal.mainDishes || meal.menuItems || "", curries: meal.curries || "", shortEats: meal.shortEats || "" }); setEditingId(meal.id); };
  const remove = async (id) => { if (!window.confirm("Remove this meal menu?")) return; try { await deleteCanteenMeal(id); await load(); } catch { setError("Could not remove the meal menu."); } };
  return <div className="max-w-5xl space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">Meal management</h1><p className="text-sm text-gray-500 mt-1">Publish breakfast, lunch, and dinner menus. Each saved menu expires automatically after 24 hours.</p></div>
    <form onSubmit={submit} className="bg-white rounded-2xl border border-gray-100 p-6 space-y-4"><div className="grid md:grid-cols-[180px_1fr] gap-4"><label className="block text-sm font-medium text-gray-700">Meal type<select value={form.mealType} onChange={(e) => setForm({ ...form, mealType: e.target.value })} className="mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5"><option value="BREAKFAST">Breakfast</option><option value="LUNCH">Lunch</option><option value="DINNER">Dinner</option></select></label><p className="text-sm text-gray-500 self-end pb-2">Add items under the appropriate category. Separate items with commas or new lines.</p></div><div className="grid md:grid-cols-3 gap-4">{[["mainDishes", "Main Dishes", "Rice, noodles, hoppers"], ["curries", "Curries", "Chicken curry, dhal curry"], ["shortEats", "Short Eats", "Rolls, cutlets, sandwiches"]].map(([field, label, placeholder]) => <label key={field} className="block text-sm font-medium text-gray-700">{label}<textarea value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} rows="3" className="mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5" placeholder={placeholder} /></label>)}</div><div className="flex items-center gap-4"><button disabled={saving} className="h-11 px-5 rounded-xl bg-orange-500 text-white font-semibold hover:bg-orange-600 disabled:opacity-60 flex items-center gap-2">{editingId ? <Pencil size={16} /> : <Plus size={16} />}{saving ? "Saving..." : editingId ? "Update" : "Publish"}</button>{editingId && <button type="button" onClick={() => { setForm(empty); setEditingId(null); }} className="text-sm text-gray-500">Cancel edit</button>}</div></form>
    {error && <p className="text-sm text-red-600">{error}</p>}
    <div className="grid md:grid-cols-3 gap-4">{["BREAKFAST", "LUNCH", "DINNER"].map((type) => { const typeMeals = meals.filter((m) => m.mealType === type); return <section key={type} className="bg-white rounded-2xl border border-gray-100 p-5"><h2 className="font-bold text-gray-800 capitalize">{type.toLowerCase()}</h2>{typeMeals.length === 0 ? <p className="text-sm text-gray-400 mt-4">No menu published.</p> : <div className="mt-4 space-y-3">{typeMeals.map((meal) => <div key={meal.id} className="rounded-xl bg-orange-50 p-3 space-y-2">{[["Main Dishes", meal.mainDishes || meal.menuItems], ["Curries", meal.curries], ["Short Eats", meal.shortEats]].filter(([, value]) => value).map(([label, value]) => <div key={label}><p className="text-[11px] uppercase font-bold text-orange-600">{label}</p><p className="text-sm text-gray-700 whitespace-pre-line">{value}</p></div>)}<p className="pt-1 text-[11px] text-gray-400">Expires {new Date(meal.expiresAt).toLocaleString()}</p><div className="flex gap-3"><button onClick={() => edit(meal)} className="text-xs font-semibold text-blue-600 flex items-center gap-1"><Pencil size={13} /> Edit</button><button onClick={() => remove(meal.id)} className="text-xs font-semibold text-red-600 flex items-center gap-1"><Trash2 size={13} /> Delete</button></div></div>)}</div>}</section>; })}</div>
  </div>;
}
